### ISSUE TITLE
support for deployment types

### ISSUE THREAD

**Issue by sholzhauer-es** [elastic/elasticsearch-chargeback#9]
Support of other platforms -> Currently this only works for ECH, because of the billing integration that we have. We would have to figure out how to calculate or configure cost on other platforms.

- [ ] ECE
- [ ] On-prem
- [ ] ECK
- [ ] Serverless

**Comment by bandarr-io** [comment]
Multiple customers across Public Sector units rely on these platforms today, representing significant business value.  

Adding customizable cost metrics would greatly enhance our ability to support these deployment types.

A practical approach would be allowing users to set their own cost basis through a simple YAML config:

```yaml
costs:
  storage_gb_month: 0.10
  ingest_gb_day: 0.05
  queries_per_1k: 0.02
  cpu_hour: 0.03
  memory_hour: 0.01
```

This lets customers define resource values aligned to their specific use cases. Then we do the math and ingest it back into a dashboard.
